- platform: rest
  name: pooldoser_ph
  resource: http://192.168.1.112/api/v1/debug/ll
  method: GET
  scan_interval: 10
  json_attributes:
    - DEVICES
  json_attributes_path: "$.DEVICES[0].params"
  value_template: "{{ (value_json.DEVICES[0].params | selectattr('id', 'eq', '@IR2000') | map(attribute='value') | first) / 100 | round(2) }}"
  unit_of_measurement: "pH"
  state_class: "measurement"

- platform: rest
  name: pooldoser_redox
  resource: http://192.168.1.112/api/v1/debug/ll
  method: GET
  scan_interval: 10
  json_attributes:
    - DEVICES
  json_attributes_path: "$.DEVICES[0].params"
  value_template: "{{ value_json.DEVICES[0].params | selectattr('id', 'eq', '@IR2001') | map(attribute='value') | first }}"
  device_class: volatile_organic_compounds_parts
  unit_of_measurement: "PPM"
  state_class: "measurement"

- platform: rest
  name: pooldoser_temp
  resource: http://192.168.1.112/api/v1/debug/ll
  method: GET
  scan_interval: 10
  json_attributes:
    - DEVICES
  json_attributes_path: "$.DEVICES[0].params"
  value_template: "{{ (value_json.DEVICES[0].params | selectattr('id', 'eq', '@IR2002') | map(attribute='value') | first) / 10 | round(1) }}"
  device_class: temperature
  unit_of_measurement: "°C"
  state_class: "measurement"
